[tool.poetry]
name = "core"
version = "1.2.0"
description = ""
authors = ["kiriharu <me@kiriha.ru>"]

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
